import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { ViewGridIcon } from "@heroicons/react/outline";
import { MicrophoneIcon, SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const searchRefinput = useRef(null);
  const router = useRouter();

  const search = (e) => {
    e.preventDefault();
    const term = searchRefinput.current.value;
    if (!term) return;
    router.push(`/search/?term=${term}`);
  };
  return (
    <div className="flex flex-col h-screen justify-center items-center">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://seeklogo.com/images/G/google-logo-28FA7991AF-seeklogo.com.png"
        />
      </Head>
      {/* header */}
      <header className="flex items-center w-full  p-5 text-sm text-gray-700 justify-between">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center text-sm">
          <p className="link">Gmail</p>
          <p className="link">images</p>
          <ViewGridIcon className="h-10 text-gray-400 p-2 w-10 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar
            url={
              "https://media-exp1.licdn.com/dms/image/C4D03AQHDJ4-kDSrfEg/profile-displayphoto-shrink_800_800/0/1620789468883?e=1666224000&v=beta&t=9d7u6SvGNArrbV8eeLBb2Jn7WaADZlhgzvbzK-9eZv4"
            }
          />
        </div>
      </header>
      {/* body */}
      <form className="flex flex-col items-center mt-40 w-4/5">
        <Image
          src={
            "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/2560px-Google_2015_logo.svg.png"
          }
          height={100}
          width={300}
        />
        <div
          className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md  rounded-full items-center py-3 px-5 border
        sm:max-w-xl lg:max-w-2xl
        "
        >
          <SearchIcon className="h-5 text-gray-500 mr-3" />
          <input
            ref={searchRefinput}
            type="text"
            className="focus:outline-none flex-grow"
            placeholder="search Google"
          />
          <MicrophoneIcon className="h-5  text-gray-500" />
        </div>
        <div className="flex flex-col space-y-3 justify-center w-1/2 mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn" onClick={search}>
            Google Search
          </button>
          <button className="btn" onClick={search}>
            I'm Feeling Lucky
          </button>
        </div>
      </form>
      {/* footer */}
      <Footer />
    </div>
  );
}
